package clases;
/*TENEMOS UN ARRAY DE 20 ELEMENTOS.

 * LLENARLO CON NUMEROS ALEATORIOS ENTRE 1 Y 100 AMBOS INCLUIDOS Y MOSTRARLO POR PANTALLA

 * BUSCAR EL MAYOR Y EL MENOR DENTRO DEL ARRAY.

 * MOSTRAR POR PANTALLA EL MÁXIMO Y EL MÍNIMO DEL ARRAY INDICANDO QUÉ POSICIONES OCUPAN

 */
public class Ejercicio_02_Arrays {
}
